### ISSUE TITLE
Compile protos on CI server

### ISSUE THREAD

**Issue by htdvisser** [TheThingsNetwork/api#1]

**Comment by rvolosatovs** [comment]
I had set up the `protoc` and all the `protobuf` stuff in a `Dockerfile` in the early days of the NOC, if you want I can look it up and maybe implement

**Comment by htdvisser** [comment]
Was that just for Go or also for the other languages?

**Comment by rvolosatovs** [comment]
that was only go, but it wouldn't be hard to compile for other languages as full latest-version `protoc` is there

**Comment by htdvisser** [comment]
Maybe you should take a look at the README, because there's quite some other stuff that needs to be installed besides `protoc`.
