### ISSUE TITLE
Refactor component gRPC clients

### ISSUE THREAD

**Issue by rvolosatovs** [TheThingsNetwork/api#10]
Clients should be refactored to work in the same way as `monitorclient`
- [ ] broker
- [x] ~handler~
- [ ] router
- [x] ~discovery~

@htdvisser do handler and network server belong here or should they be removed at all?

**Comment by htdvisser** [comment]
I think we should only create overlays for streams, as those can be complicated to use. Unary calls do not need overlays, so we probably should get rid of those in `discovery` and `handler`(manager). As far as I know, there isn't anything in `networkserver`

**Comment by rvolosatovs** [comment]
my bad, should have been `discovery`, not `network server`

**Comment by htdvisser** [comment]
Abandoning this in v2
