### ISSUE TITLE
Unused C compiled protos

### ISSUE THREAD

**Issue by rvolosatovs** [TheThingsNetwork/api#17]
https://github.com/TheThingsNetwork/api/blob/master/c/google/api/annotations.pb-c.c
https://github.com/TheThingsNetwork/api/blob/master/c/google/api/annotations.pb-c.h
These files seem to not have any useful content, is it supposed to be like this?

**Comment by htdvisser** [comment]
@johanstokking added these in https://github.com/TheThingsNetwork/ttn-gateway-connector
