### ISSUE TITLE
Add Rust support

### ISSUE THREAD

**Issue by rvolosatovs** [TheThingsNetwork/api#18]
Our `protoc` image(https://github.com/TheThingsIndustries/docker-protobuf) now supports Rust, so we just need to add a new build target to the Makefile

**Comment by MTRNord** [comment]
So I am kinda doing this for another project as a side module: https://github.com/Nucleon-eV/TTN-Rust

Feel free to add feedback or so. Its known that it propably wont build everywhere (the build.rs requires a specific path for the protobuf includes at the time I am writing this message)
