### ISSUE TITLE
Add randomizers for all message types

### ISSUE THREAD

**Issue by htdvisser** [TheThingsNetwork/api#2]
- Should be in a separate package
- Should return sensible values

See https://github.com/TheThingsNetwork/ttn/issues/658

**Comment by rvolosatovs** [comment]
If we want to be compatible with `gogoproto` stuff, the randomizers should be of form `NewPopulatedXXX`. And take a `rand` as parameter, see https://github.com/TheThingsNetwork/ttn/pull/628 for reference

**Comment by htdvisser** [comment]
Work started in https://github.com/TheThingsNetwork/api/tree/feature/2-go-populate
