### ISSUE TITLE
Internal Server Error when requesting device by uppercase deveui

### ISSUE THREAD

**Issue by janjongboom** [TheThingsNetwork/api#25]
I'm doing this:

```
GET http://eu.thethings.network:8084/applications/mbed-update/devices/00800000040004CA
```

This throws a `500 - Internal Server Error`.

Requesting `00800000040004ca` works.

@johanstokking

**Comment by johanstokking** [comment]
Thanks for the report. This should be `400 - Bad Request`, indeed not a 500. It's invalid because IDs must be lowercase and follow quite some other length and character rules. IDs are not related to EUIs either.

We'll be addressing this in V3.
