### ISSUE TITLE
make clean all fails

### ISSUE THREAD

**Issue by bkircher67** [TheThingsNetwork/api#29]
Hello, if I execute the "make clean all" command on my Ubuntu 17.10 then after a few minutes I get this message and the setup terminates:

```
make[1]: Verzeichnis „/home/bernd/ttn/api“ wird betreten
/src: warning: directory does not exist.
/home/bernd/ttn/api/protocol/protocol.proto: File does not reside within any path specified using --proto_path (or -I).  You must specify a --proto_path which encompasses this file.  Note that the proto_path must be an exact prefix of the .proto file names -- protoc is too dumb to figure out when two paths (e.g. absolute and relative) are equivalent (it's harder than you think).
Makefile:46: die Regel für Ziel „protocol/protocol.pb.go“ scheiterte
make[1]: *** [protocol/protocol.pb.go] Fehler 1
make[1]: Verzeichnis „/home/bernd/ttn/api“ wird verlassen
Makefile:37: die Regel für Ziel „protos/go“ scheiterte
make: *** [protos/go] Fehler 2
```

KR Bernd

**Comment by htdvisser** [comment]
Are you on a recent version of Docker? It looks like it doesn't understand the multi-stage build directive "FROM golang:1.10 AS go_builder" that was introduced more than a year ago with Docker 17.05.

**Comment by singularsyntax** [comment]
Yeah, it's old (the one that comes with CentOS 7):

    [vagrant@localhost ~]$ docker --version
    Docker version 1.13.1, build dded712/1.13.1

I'll try a newer version. It would be helpful to update the README with the minimum supported version.

**Comment by singularsyntax** [comment]
Different problem now, on a recent version of Docker:

    [vagrant@localhost api]$ docker --version
    Docker version 18.06.1-ce, build e68fc7a

This is the error message:

    Generating swift protos...
    make[1]: Entering directory `/vagrant/ttn-playground/api'
    make[1]: Leaving directory `/vagrant/ttn-playground/api'
    mockgen -source=./protocol/lorawan/device.pb.go -package lorawan DeviceManagerClient > protocol/lorawan/device_mock.go
    /bin/sh: mockgen: command not found
    make: *** [mocks] Error 127

**Comment by htdvisser** [comment]
Hmm, `mockgen` is a Go tool that isn't really needed if we just want to compile the protos. You could work around this by removing the `mocks` dependency from the `all` target in the Makefile (currently that's line 9).
