### ISSUE TITLE
Use github.com/grpc-ecosystem/go-grpc-middleware/validator

### ISSUE THREAD

**Issue by rvolosatovs** [TheThingsNetwork/api#3]
Let's generate validators using this package, that should be possible, no @htdvisser ?
https://github.com/grpc-ecosystem/go-grpc-middleware/tree/master/validator

**Comment by htdvisser** [comment]
After a quick look at the proposed package, I think it's a bit too simple (at the moment). We don't just have strings and numbers, but use custom types with custom validation.

Also, I already started working on validations: https://github.com/TheThingsNetwork/api/compare/feature/go-validate

**Comment by htdvisser** [comment]
Iceboxing this for now
